list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../cmake")

set(CMAKE_SYSTEM_NAME "UEFI")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")

set(CMAKE_SYSROOT "${CMAKE_CURRENT_SOURCE_DIR}/../install")
include_directories(SYSTEM "${CMAKE_SYSROOT}/include")
link_directories("${CMAKE_SYSROOT}/lib")
link_libraries("${CMAKE_SYSROOT}/lib/libc.a" "${CMAKE_SYSROOT}/lib/libc++.a")

set(CMAKE_C_COMPILER "clang")
set(CMAKE_CXX_COMPILER "clang++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
